# Generated by Django 5.0.14 on 2025-05-16 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название образовательного курса')),
                ('description', models.TextField(blank=True, help_text='Опишите цели, программу и ожидаемые результаты курса', null=True, verbose_name='Подробное описание курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('slug', models.SlugField(blank=True, help_text='URL-идентификатор курса', max_length=150, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор курса')),
            ],
            options={
                'verbose_name': 'Образовательный курс',
                'verbose_name_plural': 'Образовательные курсы',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Опишите материалы и задания урока', null=True, verbose_name='Содержание урока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в курсе')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learning_platform.course', verbose_name='Входит в курс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учебный материал',
                'verbose_name_plural': 'Учебные материалы',
                'ordering': ['course', 'order', 'name'],
                'permissions': [('view_lesson_content', 'Может просматривать содержание урока'), ('submit_lesson_work', 'Может отправлять работы по уроку')],
            },
        ),
    ]
